### ISSUE TITLE
Chào chú

### ISSUE THREAD

**Issue by dattrannh** [thaitni/xbmc.repo.xshare#7]

**Comment by thaitni** [comment]
Chào bạn!
Vấn đề này là yếu tố quyết định của một add-on media.

Việc lấy direct link của một link phim bất kỳ phụ thuộc vào rất nhiều yếu tố.
Ví dụ:
- Của các site có thu phí thì mình phải mua acc VIP của họ. (Fshare, ...)
- Của các site free thì cũng tùy rất nhiều vào thiết kế của từng trang. Có nhiều trang họ mã hóa link và cũng có nhiều trang không.

Nếu gặp trang mã hóa thì mình phải tìm module giải mã (ngay tren site của họ).

Nếu bạn muốn tìm hiểu sâu hơn về vấn đề này thì bạn có thể tham khảo ngay muc hdonline (dễ nhất) của xshare. Nếu sau khi đọc code, bạn chưa hiểu chổ nào thì mình sẽ giúp bạn.

Chúc bạn thành công.

**Comment by dattrannh** [comment]
xin cảm ơn bác

Vào 16:01 Ngày 27 tháng 10 năm 2016, Trương Thành Thái <
notifications@github.com> đã viết:
